/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemacontable;

import com.toedter.calendar.JDateChooser;
import dbconnection.DatabaseConnection;
import dbconnectionQueries.Create;
import dbconnectionQueries.Select;
import java.awt.Component;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.Locale;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author PC
 */
public class Ingreso_Partidas extends javax.swing.JFrame {

    private DefaultTableModel model = null;

    public boolean isNumber(String str) {
        return str.matches("-?\\d+(\\.\\d+)?");
    }



    private void resetData(){

        model = new DefaultTableModel(null, new String [] {
                "Fecha", "Cuenta", "Código", "Debe", "Haber"
        });

        jTableDaily.setModel(model);
    }

    /**
     * Creates new form Ingreso_Partidas
     */
    public Ingreso_Partidas() {
        initComponents();
        resetData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDaily = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnRegistry = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jcomboSelectAccountType = new javax.swing.JComboBox<>();
        btnNewAccount = new javax.swing.JButton();
        jComboSelectAccountTitle = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de partidas");
        setName("Registro de partidas"); // NOI18N
        setResizable(false);

        jPanel1.setName("Contenedor"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setName("panelContenido"); // NOI18N

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableDaily.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Titulo", "Codigo", "Debe", "Haber"
            }
        ));
        jScrollPane2.setViewportView(jTableDaily);

        btnCancelar.setBackground(new java.awt.Color(71, 102, 121));
        btnCancelar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnRegistry.setBackground(new java.awt.Color(71, 102, 121));
        btnRegistry.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRegistry.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ahorrar.png"))); // NOI18N
        btnRegistry.setText("Registrar");
        btnRegistry.setEnabled(false);
        btnRegistry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistryActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("REGISTRO DE PARTIDAS");

        jDateChooser.setBackground(new java.awt.Color(71, 102, 121));
        jDateChooser.setForeground(new java.awt.Color(255, 255, 255));

        jcomboSelectAccountType.setBackground(new java.awt.Color(71, 102, 121));
        jcomboSelectAccountType.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcomboSelectAccountType.setForeground(new java.awt.Color(255, 255, 255));
        jcomboSelectAccountType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar tipo de cuenta", "Activo", "Pasivo", "Patrimonio", "Cierre" }));
        jcomboSelectAccountType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboSelectAccountTypeActionPerformed(evt);
            }
        });

        btnNewAccount.setBackground(new java.awt.Color(71, 102, 121));
        btnNewAccount.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnNewAccount.setForeground(new java.awt.Color(255, 255, 255));
        btnNewAccount.setText("Nueva partida");
        btnNewAccount.setEnabled(false);
        btnNewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAccountActionPerformed(evt);
            }
        });

        jComboSelectAccountTitle.setBackground(new java.awt.Color(71, 102, 121));
        jComboSelectAccountTitle.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jComboSelectAccountTitle.setForeground(new java.awt.Color(255, 255, 255));
        jComboSelectAccountTitle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar cuenta" }));
        jComboSelectAccountTitle.setEnabled(false);
        jComboSelectAccountTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboSelectAccountTitleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jcomboSelectAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jComboSelectAccountTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnNewAccount))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistry)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcomboSelectAccountType)
                    .addComponent(btnNewAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jComboSelectAccountTitle))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(btnRegistry, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAccountActionPerformed
        String date = jDateChooser.getDateFormatString();
        String accountTitle = (String) jComboSelectAccountTitle.getSelectedItem();
        String debit = JOptionPane.showInputDialog(null, "Debe: ", "Ingrese la cantidad en debe", JOptionPane.PLAIN_MESSAGE);
        String credit = JOptionPane.showInputDialog(null, "Haber: ", "Ingrese la cantidad en haber", JOptionPane.PLAIN_MESSAGE);

    }//GEN-LAST:event_btnNewAccountActionPerformed

    private void btnAddNewRowActionPerformed(java.awt.event.ActionEvent evt) {
        DefaultTableModel model = (DefaultTableModel) jTableDaily.getModel();

        // Crea una nueva fila con valores iniciales vacíos, incluyendo componentes
        Object[] newRow = new Object[]{
                "",
                "",
                "",
                "",
                ""
        };

        // Agrega la nueva fila al modelo de la tabla
        model.addRow(newRow);
        jTableDaily.setRowHeight(30);
    }

    private void jcomboSelectAccountTypeActionPerformed(java.awt.event.ActionEvent evt) {
        if (jcomboSelectAccountType.getSelectedIndex() != 0) {
            Object selectedObject = jcomboSelectAccountType.getSelectedItem();
            String selected = selectedObject.toString();
            Select s = new Select();
            ResultSet queryResult = s.getAccounts(selected);

            // Habilita el JComboBox
            jComboSelectAccountTitle.setEnabled(true);
            // Borra los elementos existentes en el JComboBox
            jComboSelectAccountTitle.removeAllItems();

            try {
                while (queryResult.next()) {
                    // Agrega los elementos al JComboBox utilizando getString(2) para obtener el valor de la primera columna
                    String originalText = queryResult.getString(2);
                    if (queryResult.getString(1).length() == 2) {
                        originalText = "   " + originalText; // Agrega dos espacios iniciales
                        String capitalizedText = originalText.substring(0, 4).toUpperCase() + originalText.substring(4).toLowerCase();
                        jComboSelectAccountTitle.addItem(capitalizedText);
                    }
                    else if (queryResult.getString(1).length() >= 4) {
                        originalText = "     " + originalText; // Agrega dos espacios iniciales
                        String capitalizedText = originalText.substring(0, 6).toUpperCase() + originalText.substring(6).toLowerCase();
                        jComboSelectAccountTitle.addItem(capitalizedText);
                    }
                    else {
                        String capitalizedText = originalText.substring(0, 1).toUpperCase() + originalText.substring(1).toLowerCase();
                        jComboSelectAccountTitle.addItem(capitalizedText);
                    }
                }
            } catch (SQLException e) {
                throw new RuntimeException(e);
            }
        } else {
            // Deshabilita el JComboBox y borra los elementos
            jComboSelectAccountTitle.setEnabled(false);
            jComboSelectAccountTitle.removeAllItems();
            btnRegistry.setEnabled(false);
            btnNewAccount.setEnabled(false);
        }
    }

    private void jComboSelectAccountTitleActionPerformed(java.awt.event.ActionEvent evt) {
        if(jComboSelectAccountTitle.getSelectedIndex() == 0){
            btnRegistry.setEnabled(false);
            btnNewAccount.setEnabled(false);
            return;
        }
        btnRegistry.setEnabled(true);
        btnNewAccount.setEnabled(true);
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        this.dispose();
    }

    private void btnRegistryActionPerformed(java.awt.event.ActionEvent evt) {                                            
        btnRegistry.setFocusPainted(false);


        DefaultTableModel defaultTableModel = new DefaultTableModel();
        
        

//        model.addRow(data);
//        for (int i = 0; i < data.length; i++){
//            System.out.println("Data: " + data[i]);
//        }
//
//        int rowsCount = model.getRowCount();
//        int columnsCount = model.getColumnCount();
//        List<String []> rows = new ArrayList<>();
//
//        for (int i = 0; i < rowsCount; i++) {
//            String [] filaActual = new String[columnsCount];
//            for (int j = 0; j < columnsCount; j++) {
//                filaActual[j] = (String) model.getValueAt(i, j);
//            }
//            rows.add(filaActual);
//        }
//
//
//        for (int i = 0; i < rows.size(); i++) {
//            for (int j = 0; j < rows.get(i).length; j++) {
//
//                System.out.println(model.getColumnName(j) + ": " + rows.get(i)[j]);
//            }
//            System.out.println();
//        }
//
//        Create c = new Create();
//        c.saveDaily(data);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Partidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Partidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Partidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Partidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingreso_Partidas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnNewAccount;
    private javax.swing.JButton btnRegistry;
    private javax.swing.JComboBox<String> jComboSelectAccountTitle;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableDaily;
    private javax.swing.JComboBox<String> jcomboSelectAccountType;
    // End of variables declaration//GEN-END:variables
}
