/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sistemacontable;

import dbconnectionQueries.Select;

import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;

/**
 *
 * @author EstudianteFMO
 */
public class LIbroMayor extends javax.swing.JPanel {

    /**
     * Creates new form LIbroMAyor
     */
    public LIbroMayor() {
        initComponents();
        loadAccounts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGeneral = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableResults = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(213, 219, 231));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("LIBRO MAYOR");

        jSeparator1.setForeground(new java.awt.Color(0, 102, 102));

        jTableGeneral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Cuenta", "Debe", "Haber"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableGeneral);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Libro Mayor", jPanel3);

        jTableResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cuenta", "Resultado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableResults);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Resultados", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Carga datos de cuentas en la tabla jTableGeneral a partir de una consulta a la base de datos.
     * Después de cargar los datos, se ajusta la altura de las filas y se realiza una limpieza de títulos de cuentas duplicados y celdas de débito/crédito con valor "0".
     *
     * Nota: Se espera que jTableGeneral tenga las columnas "fecha", "cuenta", "debe" y "haber" en ese orden.
     */
    private void loadAccounts() {
        try {
            // Crear una instancia de la clase Select para realizar consultas
            Select s = new Select();

            // Obtener un conjunto de resultados (ResultSet) con los datos de cuentas
            ResultSet rs = s.loadAccountsToGeneralBook();

            // Obtener el modelo de datos de la tabla jTableGeneral
            DefaultTableModel myModel = (DefaultTableModel) jTableGeneral.getModel();

            // Recorrer los resultados y agregarlos a la tabla
            while (rs.next()) {
                String fecha = rs.getString(1);
                String cuenta = rs.getString(2);
                String debe = rs.getString(4);
                String haber = rs.getString(5);

                // Crear un nuevo arreglo de objetos con los valores
                Object[] newRow = {
                        fecha,
                        cuenta,
                        debe,
                        haber
                };

                // Agregar la nueva fila al modelo de datos de la tabla jTableGeneral
                myModel.addRow(newRow);

                // Ajustar la altura de las filas en la tabla
                jTableGeneral.setRowHeight(30);
            }

            // Verificar si la tabla tiene columnas y realizar la limpieza de datos si es necesario
            if (jTableGeneral.getColumnCount() > 0) {
                cleanUpSameAccountTitle(myModel);
            }
        } catch (Exception e) {
            // Capturar y lanzar una excepción en caso de error
            throw new RuntimeException(e);
        }
    }


    /**
     * Realiza operaciones de limpieza en un modelo de datos de tabla, eliminando títulos de cuenta duplicados y celdas de débito/crédito con valor "0".
     * Después de la limpieza, se invoca el método `getSum()` para calcular los saldos actualizados.
     *
     * @param myModel El modelo de datos de la tabla a limpiar.
     */
    private void cleanUpSameAccountTitle(DefaultTableModel myModel) {
        // Definir las columnas utilizadas en el modelo de datos
        final int columnAccount = 1;
        final int columnDebit = 2;
        final int columnCredit = 3;

        // Variable para almacenar el valor de cuenta anterior
        String valorAnteriorAccount = "";

        // Recorrer las filas del modelo de datos de la tabla
        for (int fila = 0; fila < myModel.getRowCount(); fila++) {
            // Obtener los valores de las celdas en las columnas relevantes
            Object valorAccount = myModel.getValueAt(fila, columnAccount);
            Object valorDebit = myModel.getValueAt(fila, columnDebit);
            Object valorCredit = myModel.getValueAt(fila, columnCredit);

            // Verificar si el valor de cuenta actual es igual al valor de cuenta anterior
            if (valorAccount.equals(valorAnteriorAccount)) {
                // Si son iguales, eliminar el título de cuenta en la celda
                myModel.setValueAt("", fila, columnAccount);
            } else {
                // Si son diferentes, actualizar el valor de cuenta anterior
                valorAnteriorAccount = valorAccount.toString();
            }

            // Verificar si el valor de débito es "0" y eliminarlo si es el caso
            if (valorDebit.equals("0")) {
                myModel.setValueAt("", fila, columnDebit);
            }

            // Verificar si el valor de crédito es "0" y eliminarlo si es el caso
            if (valorCredit.equals("0")) {
                myModel.setValueAt("", fila, columnCredit);
            }
        }

        // Calcular los saldos actualizados después de la limpieza
        getSum();
    }


    //Agregar suma de columnas hasta que la cuenta cambie:
    /**
     * Calcula el saldo de cuentas a partir de datos en una tabla y muestra los resultados en otra.
     */
    private void getSum() {
        // Crear una instancia del objeto Select
        Select s = new Select();

        // Obtener el modelo de datos de la tabla jTableGeneral
        DefaultTableModel myModel = (DefaultTableModel) jTableGeneral.getModel();

        // Obtener el modelo de datos de la tabla jTableResults
        DefaultTableModel myResultsModel = (DefaultTableModel) jTableResults.getModel();

        // Inicializar variables para almacenar la suma de débitos y créditos
        double sumDebit = 0;
        double sumCredit = 0;

        // Definir las columnas utilizadas en el proceso
        final int columnAccount = 1;
        final int columnResult = 2;

        // Recorrer las filas de la tabla jTableGeneral
        for (int n = 0; n < myModel.getRowCount(); n++) {
            // Obtener el valor de la celda en la columna de cuentas
            String currentValue = (String) myModel.getValueAt(n, columnAccount);
            if(!currentValue.isEmpty()){
                // Obtener el resultado de la suma de débitos y créditos para la cuenta actual
                ResultSet rsDebit = s.getSumFromDebit(currentValue);
                ResultSet rsCredit = s.getSumFromCredit(currentValue);

                try {
                    while (rsDebit.next()) {
                        sumDebit = rsDebit.getDouble(1);
                    }

                    while (rsCredit.next()) {
                        sumCredit = rsCredit.getDouble(1);
                    }

                    // Calcular el saldo
                    double balance = sumDebit - sumCredit;

                    // Actualizar los valores en el modelo de datos de la tabla jTableResults
                    if (n < myResultsModel.getRowCount()) {
                        myResultsModel.setValueAt(currentValue, n, 0);
                        myResultsModel.setValueAt(balance, n, 1);
                    } else {
                        myResultsModel.addRow(new Object[]{currentValue, balance});
                    }
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
            }
        }

        // Realizar limpieza de la tabla jTableResults
        cleanUpResultsTable();

        // Crear una instancia del renderizador personalizado para la columna de débitos en jTableResults
        RenderGeneralBookColourResults colorRenderer = new RenderGeneralBookColourResults();
        jTableResults.getColumnModel().getColumn(1).setCellRenderer(colorRenderer);
    }


    private void cleanUpResultsTable(){
        DefaultTableModel myResultsModel = (DefaultTableModel) jTableResults.getModel();

        for(int n = 0; n < myResultsModel.getRowCount(); n++){
            if(myResultsModel.getValueAt(n,0).equals("")){
                myResultsModel.removeRow(n);
            }
        }

        jTableResults.setRowHeight(30);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableGeneral;
    private javax.swing.JTable jTableResults;
    // End of variables declaration//GEN-END:variables
}
