/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sistemacontable;

import dbconnectionQueries.Select1;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author angel
 */
public class Mayor extends javax.swing.JPanel {

    /**
     * Creates new form Mayor
     */
    public Mayor() {
        initComponents();
        createAndShowGUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setLayout(new java.awt.GridLayout(0, 1, 10, 10));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2);

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
private void createAndShowGUI() {
        try {
            Select1 select = new Select1();

            ResultSet rs = select.obtenerNombresCuentas();

            if (rs.next()){
                do {
                    JTable table = createTable(rs.getString("cuenta"));
                    if (table.getRowCount() != 0){
                        JScrollPane scrollPane = new JScrollPane(table);

                        // Configura el tamaño preferido del área visible de la tabla
                        table.setPreferredScrollableViewportSize(table.getPreferredSize());

                        jPanel1.add(scrollPane);
                    }
                }while (rs.next());
            }
        }catch (SQLException ignored){
        } catch (Exception ex) {
            Logger.getLogger(Mayor.class.getName()).log(Level.SEVERE, null, ex);
        }


        /*// Agregar 20 tablas
        for (int i = 1; i <= 20; i++) {
            JTable table = createTable();
            JScrollPane scrollPane = new JScrollPane(table);

            // Configura el tamaño preferido del área visible de la tabla
            table.setPreferredScrollableViewportSize(table.getPreferredSize());

            panel.add(scrollPane);
        }

        frame.add(new JScrollPane(panel));
        frame.setVisible(true);*/
    }
    
    private static JTable createTable(String nombreCuenta) throws Exception {

        try {
            Select1 select = new Select1();

            ResultSet rs = select.obtenerDeberHaberPorCuenta(nombreCuenta);

            List<Double> listaDeber = new ArrayList<>();
            List<Double> listaHaber = new ArrayList<>();

            if (rs.next()){
                do {
                    double deber = rs.getDouble("debe");
                    double haber = rs.getDouble("haber");


                    if (deber != 0.0){
                        listaDeber.add(deber);
                    }
                    if (haber != 0){
                        listaHaber.add(haber);
                        System.out.println("entro");
                    }
                }while (rs.next());
            }

            System.out.println(listaDeber.size());
            System.out.println(listaHaber.size());

            int mayor = Math.max(listaDeber.size(), listaHaber.size());


            String[] columnNames = {nombreCuenta, ""};
            DefaultTableModel model = new DefaultTableModel(null, columnNames){
                @Override
                public boolean isCellEditable (int row, int column) {
                    return false;
                }
            };

            model.addRow(new Object[]{"Debe", "Haber"});

            for (int i = 0; i < mayor; i++) {
                String[] strings = new String[]{"", ""};
                model.addRow(strings);
            }

            System.out.println("Numero de filas: " + model.getRowCount());
            System.out.println("Numero de valores en haber y deber: " + listaHaber.size() + " - " + listaDeber.size());

            for (int i = 0; i < listaDeber.size(); i++) model.setValueAt(String.valueOf(listaDeber.get(i)), i+1, 0);
            for (int i = 0; i < listaHaber.size(); i++) model.setValueAt(String.valueOf(listaHaber.get(i)), i+1, 1);


            return new JTable(model);

        }catch (Exception ignored){
            System.err.println(ignored);
        }
            throw new RuntimeException();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
